-- Schema principal AD Bela-Vista
-- Rode este arquivo primeiro no SQL Editor do Supabase.
-- Depois rode, nesta ordem:
-- 1) public/db/supabase-secretario.sql
-- 2) public/db/supabase-membro.sql
-- 3) public/db/supabase-security-hardening.sql

create extension if not exists pgcrypto;

grant usage on schema public to anon, authenticated;
grant usage on schema extensions to anon, authenticated;
revoke create on schema public from public;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'secretario',
  created_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists role text not null default 'secretario';

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles
  add constraint profiles_role_check
  check (role in ('admin', 'pastor', 'secretario'));

create table if not exists public.member_accounts (
  id uuid primary key default extensions.gen_random_uuid(),
  first_name text not null,
  last_name text not null,
  email text not null unique,
  phone text not null,
  cpf text unique,
  avatar_url text,
  password_hash text not null,
  privacy_accepted_at timestamptz,
  privacy_version text,
  privacy_source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz
);

create table if not exists public.member_account_sessions (
  id uuid primary key default extensions.gen_random_uuid(),
  account_id uuid not null references public.member_accounts(id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '30 days'
);

create table if not exists public.member_login_attempts (
  email_hash text primary key,
  failed_attempts integer not null default 0,
  first_failed_at timestamptz not null default now(),
  locked_until timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.system_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.membros (
  id uuid primary key default extensions.gen_random_uuid(),
  tipo_cadastro text,
  status text not null default 'Pendente',
  tipo_cpf text,
  nome text not null,
  rg text,
  cpf text,
  data_nasc date,
  idade integer,
  sexo text,
  tipo_sanguineo text,
  escolaridade text,
  estado_civil text,
  conjuge_nome text,
  data_casamento date,
  cep text,
  bairro text,
  endereco text,
  cidade_estado text,
  fone_res text,
  fone_com text,
  celular text,
  email text,
  ocupacao text,
  empresa text,
  forma_recebimento text,
  setor_igreja text,
  congregacao_igreja text,
  igreja_anterior text,
  igreja_cidade text,
  igreja_pastor text,
  data_batismo_aguas date,
  data_batismo_es date,
  data_aprovacao date,
  cargo_principal text,
  outras_funcoes text,
  qtd_filhos integer default 0,
  nome_dep1 text,
  parentesco_dep1 text,
  nome_dep2 text,
  parentesco_dep2 text,
  nome_dep3 text,
  parentesco_dep3 text,
  talentos text,
  tem_computador text,
  tem_internet text,
  foto_url text,
  doc_url text,
  foto_certidao_nasc text,
  foto_certidao_casamento text,
  foto_diploma text,
  foto_comprovante_end text,
  assinatura_url text,
  privacy_accepted_at timestamptz,
  privacy_version text,
  privacy_source text,
  member_account_id uuid references public.member_accounts(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid,
  actor_role text,
  action text not null,
  table_name text not null,
  record_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_member_account_sessions_account_id
  on public.member_account_sessions(account_id);

create index if not exists idx_member_account_sessions_expires_at
  on public.member_account_sessions(expires_at);

create index if not exists idx_member_login_attempts_updated_at
  on public.member_login_attempts(updated_at);

create index if not exists idx_membros_member_account_id
  on public.membros(member_account_id);

create index if not exists idx_membros_nome
  on public.membros(nome);

create index if not exists idx_membros_cpf
  on public.membros(cpf);

create index if not exists idx_membros_status
  on public.membros(status);

create index if not exists idx_membros_tipo_cadastro
  on public.membros(tipo_cadastro);

alter table public.profiles enable row level security;
alter table public.member_accounts enable row level security;
alter table public.member_account_sessions enable row level security;
alter table public.member_login_attempts enable row level security;
alter table public.system_settings enable row level security;
alter table public.membros enable row level security;
alter table public.audit_logs enable row level security;

notify pgrst, 'reload schema';
