-- Endurecimento de seguranca AD Bela-Vista
-- Rode no SQL Editor do Supabase depois dos scripts de schema/roles existentes.
-- Este arquivo e idempotente: pode ser executado novamente quando precisar.

create extension if not exists pgcrypto;

grant usage on schema public to anon, authenticated;
grant usage on schema extensions to anon, authenticated;
revoke create on schema public from public;

-- Impede acesso direto a credenciais, sessoes e tentativas de login. O acesso
-- legitimo ocorre somente pelas funcoes SECURITY DEFINER do fluxo de membros.
alter table public.member_accounts enable row level security;
alter table public.member_account_sessions enable row level security;

create table if not exists public.member_login_attempts (
  email_hash text primary key,
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  first_failed_at timestamptz not null default now(),
  locked_until timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.member_login_attempts enable row level security;
revoke all on table public.member_accounts from anon, authenticated;
revoke all on table public.member_account_sessions from anon, authenticated;
revoke all on table public.member_login_attempts from anon, authenticated;

-- Limites de tamanho evitam payloads excessivos fora da interface.
alter table public.member_accounts drop constraint if exists member_accounts_input_lengths;
alter table public.member_accounts
  add constraint member_accounts_input_lengths check (
    length(first_name) between 2 and 80
    and length(last_name) between 2 and 120
    and length(email) between 5 and 254
    and length(phone) between 10 and 30
    and (avatar_url is null or length(avatar_url) <= 2048)
  ) not valid;

alter table public.member_account_sessions
  drop constraint if exists member_sessions_valid_values;
alter table public.member_account_sessions
  add constraint member_sessions_valid_values check (
    length(token_hash) = 64
    and expires_at > created_at
    and expires_at <= created_at + interval '31 days'
  ) not valid;

alter table public.member_login_attempts
  drop constraint if exists member_login_attempts_valid_values;
alter table public.member_login_attempts
  add constraint member_login_attempts_valid_values check (
    length(email_hash) = 64
    and failed_attempts between 0 and 100
    and (locked_until is null or locked_until >= first_failed_at)
  ) not valid;

create index if not exists idx_member_login_attempts_updated_at
  on public.member_login_attempts(updated_at);

create or replace function public.member_cleanup_security_state()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.member_account_sessions
  where expires_at <= now();

  delete from public.member_login_attempts
  where updated_at < now() - interval '24 hours';
$$;

revoke all on function public.member_cleanup_security_state() from public;

-- 1) Roles administrativas
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'secretario',
  created_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists role text not null default 'secretario';

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles
  add constraint profiles_role_check
  check (role in ('admin', 'pastor', 'secretario'));

alter table public.profiles enable row level security;

create or replace function public.tem_role(roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = any(roles)
  );
$$;

revoke all on function public.tem_role(text[]) from public;
grant execute on function public.tem_role(text[]) to authenticated;

drop policy if exists "Usuario ve proprio perfil" on public.profiles;
create policy "Usuario ve proprio perfil"
on public.profiles
for select
to authenticated
using (id = auth.uid());

drop policy if exists "Admin ve perfis" on public.profiles;
create policy "Admin ve perfis"
on public.profiles
for select
to authenticated
using (public.tem_role(array['admin', 'pastor']));

drop policy if exists "Admin gerencia perfis" on public.profiles;
create policy "Admin gerencia perfis"
on public.profiles
for all
to authenticated
using (public.tem_role(array['admin']))
with check (public.tem_role(array['admin']));

-- 2) Auditoria basica
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid,
  actor_role text,
  action text not null,
  table_name text not null,
  record_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.audit_logs enable row level security;
revoke insert, update, delete, truncate on table public.audit_logs from anon, authenticated;

drop policy if exists "Admin e pastor leem auditoria" on public.audit_logs;
create policy "Admin e pastor leem auditoria"
on public.audit_logs
for select
to authenticated
using (public.tem_role(array['admin', 'pastor']));

drop policy if exists "Ninguem altera auditoria pela API" on public.audit_logs;
create policy "Ninguem altera auditoria pela API"
on public.audit_logs
for all
to authenticated
using (false)
with check (false);

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.role
  from public.profiles p
  where p.id = auth.uid()
  limit 1;
$$;

revoke all on function public.current_profile_role() from public;
grant execute on function public.current_profile_role() to authenticated;

create or replace function public.audit_membros_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_action text;
  v_record_id uuid;
  v_details jsonb;
begin
  if tg_op = 'INSERT' then
    v_action := 'insert';
    v_record_id := new.id;
    v_details := jsonb_build_object('nome', new.nome, 'tipo_cadastro', new.tipo_cadastro);
  elsif tg_op = 'UPDATE' then
    v_action := 'update';
    v_record_id := new.id;
    v_details := jsonb_build_object(
      'nome', new.nome,
      'status_before', old.status,
      'status_after', new.status
    );
  else
    v_action := 'delete';
    v_record_id := old.id;
    v_details := jsonb_build_object('nome', old.nome, 'tipo_cadastro', old.tipo_cadastro);
  end if;

  insert into public.audit_logs (actor_id, actor_role, action, table_name, record_id, details)
  values (auth.uid(), public.current_profile_role(), v_action, 'membros', v_record_id, v_details);

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

drop trigger if exists audit_membros_changes_trg on public.membros;
create trigger audit_membros_changes_trg
after insert or update or delete on public.membros
for each row
execute function public.audit_membros_changes();

-- 3) RLS da tabela membros
alter table public.membros enable row level security;

create or replace function public.validar_cadastro_publico_membros()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() = 'anon' then
    new.tipo_cadastro := nullif(trim(coalesce(new.tipo_cadastro, '')), '');
    new.nome := nullif(trim(coalesce(new.nome, '')), '');
    new.cpf := nullif(trim(coalesce(new.cpf, '')), '');
    new.celular := nullif(trim(coalesce(new.celular, '')), '');
    new.status := 'Pendente';
    new.member_account_id := null;
    new.data_aprovacao := null;

    if new.tipo_cadastro not in ('Membro', 'Congregado')
      or new.nome is null
      or length(new.nome) not between 3 and 160
      or length(regexp_replace(coalesce(new.cpf, ''), '\D', '', 'g')) < 4
      or length(regexp_replace(coalesce(new.celular, ''), '\D', '', 'g')) < 10 then
      raise exception 'Dados de cadastro invalidos.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists validar_cadastro_publico_membros_trg on public.membros;
create trigger validar_cadastro_publico_membros_trg
before insert on public.membros
for each row execute function public.validar_cadastro_publico_membros();

drop policy if exists "Admin ve todos membros" on public.membros;
create policy "Admin ve todos membros"
on public.membros
for select
to authenticated
using (public.tem_role(array['admin', 'pastor']));

drop policy if exists "Secretaria busca membros por funcao" on public.membros;
create policy "Secretaria busca membros por funcao"
on public.membros
for select
to authenticated
using (false);

drop policy if exists "Cadastro publico insere membros" on public.membros;
create policy "Cadastro publico insere membros"
on public.membros
for insert
to anon
with check (
  tipo_cadastro in ('Membro', 'Congregado')
  and coalesce(status, 'Pendente') = 'Pendente'
  and length(trim(coalesce(nome, ''))) between 3 and 160
  and length(regexp_replace(coalesce(cpf, ''), '\D', '', 'g')) >= 4
  and length(regexp_replace(coalesce(celular, ''), '\D', '', 'g')) >= 10
);

drop policy if exists "Admin e secretaria inserem membros" on public.membros;
create policy "Admin e secretaria inserem membros"
on public.membros
for insert
to authenticated
with check (public.tem_role(array['admin', 'pastor', 'secretario']));

drop policy if exists "Admin e secretaria atualizam membros" on public.membros;
create policy "Admin e secretaria atualizam membros"
on public.membros
for update
to authenticated
using (public.tem_role(array['admin', 'pastor', 'secretario']))
with check (public.tem_role(array['admin', 'pastor', 'secretario']));

drop policy if exists "Admin exclui membros" on public.membros;
create policy "Admin exclui membros"
on public.membros
for delete
to authenticated
using (public.tem_role(array['admin']));

-- 4) Storage privado de documentos/fotos
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'membros-docs',
  'membros-docs',
  false,
  6291456,
  array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']::text[]
)
on conflict (id) do update
set public = false,
    file_size_limit = 6291456,
    allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']::text[];

drop policy if exists "Equipe envia arquivos membros-docs" on storage.objects;
create policy "Equipe envia arquivos membros-docs"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'membros-docs'
  and public.tem_role(array['admin', 'pastor', 'secretario'])
);

drop policy if exists "Equipe le arquivos membros-docs" on storage.objects;
create policy "Equipe le arquivos membros-docs"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'membros-docs'
  and public.tem_role(array['admin', 'pastor', 'secretario'])
);

drop policy if exists "Equipe atualiza arquivos membros-docs" on storage.objects;
create policy "Equipe atualiza arquivos membros-docs"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'membros-docs'
  and public.tem_role(array['admin', 'pastor', 'secretario'])
)
with check (
  bucket_id = 'membros-docs'
  and public.tem_role(array['admin', 'pastor', 'secretario'])
);

drop policy if exists "Admin remove arquivos membros-docs" on storage.objects;
create policy "Admin remove arquivos membros-docs"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'membros-docs'
  and public.tem_role(array['admin'])
);

-- 5) Funcoes RPC sensiveis
revoke all on function public.admin_save_pastor_signature(text, text, text) from public;
grant execute on function public.admin_save_pastor_signature(text, text, text) to authenticated;

-- 6) Como promover usuarios:
-- insert into public.profiles (id, role)
-- select id, 'admin' from auth.users where email = 'email-do-admin@dominio.com'
-- on conflict (id) do update set role = excluded.role;
--
-- insert into public.profiles (id, role)
-- select id, 'pastor' from auth.users where email = 'email-do-pastor@dominio.com'
-- on conflict (id) do update set role = excluded.role;

notify pgrst, 'reload schema';
